# название приложения
app:
  name: Kotlin Spring Boot MyBatis
  version: 0.0.1-SNAPSHOT
# локальнй порт
server.port: 8098

spring:

# flyway migration
  flyway:
#    locations: classpath:/db/migration,classpath:/dev/db/migration
    baselineOnMigrate: true
    schemas: prototype

# database connection
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      schema: prototype

# mybatis configuration
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
