/*
 * Copyright (c) 2020. Prototype
 */

export const CLEAR_ALL_STATES = 'CLEAR_ALL_STATES';
export const GLOBAL_SHOW_LOADER = 'GLOBAL_SHOW_LOADER';
export const GLOBAL_HIDE_LOADER = 'GLOBAL_HIDE_LOADER';
export const GLOBAL_PUSH_ERROR = 'GLOBAL_PUSH_ERROR';
export const GLOBAL_CLEAR_ERROR = 'GLOBAL_CLEAR_ERROR';
export const GLOBAL_GET_USER_INFO = 'GLOBAL_GET_USER_INFO';
export const GLOBAL_GET_USER_INFO_START = 'GLOBAL_GET_USER_INFO_START';
export const GLOBAL_GET_USER_INFO_SUCCESS = 'GLOBAL_GET_USER_INFO_SUCCESS';
export const GLOBAL_GET_USER_INFO_FAIL = 'GLOBAL_GET_USER_INFO_FAIL';
export const GLOBAL_GET_SYSTEM_SETTINGS = 'GLOBAL_GET_SYSTEM_SETTINGS';
export const GLOBAL_SET_COLOR_STYLE = 'GLOBAL_SET_COLOR_STYLE';

